name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.HOST_FTP_SERVER }}
          username: ${{ secrets.HOST_FTP_USERNAME }}
          password: ${{ secrets.HOST_FTP_PASSWORD }}
          server-dir: /domains/aniketgolhar.in/public_html/SalesCRM/

      - name: Run Laravel Commands
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST_SSH_HOST }}
          username: ${{ secrets.HOST_SSH_USERNAME }}
          password: ${{ secrets.HOST_SSH_PASSWORD }}
          port: ${{ secrets.HOST_SSH_PORT }}
          script: |
            cd domains/aniketgolhar.in/public_html/SalesCRM
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan down --render="errors::503" || true
            php artisan migrate --force
            php artisan db:seed
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link || true
            rm -rf build
            cp -r public/build .
            php artisan up